language: python

# use container-based infrastructure
sudo: false

deploy:
  provider: pypi
  user: cheffe
  password:
    secure: ZQsqnd4Ux3erP0xfLJefJ/90wcJX/L2SfYOZFPbAIwJaX3n9iXf7jOGaT5FzJxLH+c0RJ1varqX0WZo1v0YKRz05IiSCLfZIT3Ia/Cy4nOLLL4a6CFUqzTlO7V1xyKMtQKimWGF5AYTAWvLTPu7cdDeg1YPENrZBYZPvJ/yRiJ4=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: baztian/jaydebeapi

cache:
  pip: true
  directories:
  - $TRAVIS_BUILD_DIR/.tox/shared/.m2
  - $HOME/jython

python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.6'

env:
matrix:
  include:
    - python: 3.6
      env: JYTHON=org.python:jython-installer:2.7.0 TOXENV="jython-driver-{hsqldb,mock}"

before_install:
  - ci/before_install.sh
  - export PATH="$HOME/bin:$PATH"

install:
  - pip install coveralls
  - pip install tox-travis

script: tox

after_success:
  - coveralls
