language: python

# use container-based infrastructure
sudo: false

deploy:
  provider: pypi
  user: cheffe
  password:
    secure: ZQsqnd4Ux3erP0xfLJefJ/90wcJX/L2SfYOZFPbAIwJaX3n9iXf7jOGaT5FzJxLH+c0RJ1varqX0WZo1v0YKRz05IiSCLfZIT3Ia/Cy4nOLLL4a6CFUqzTlO7V1xyKMtQKimWGF5AYTAWvLTPu7cdDeg1YPENrZBYZPvJ/yRiJ4=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: baztian/jaydebeapi

python:
  - '2.6'
  - '2.7'
  - '3.4'

env:
  matrix:
    - TESTNAME=test_mock JDBC_DRIVER=org.jaydebeapi:mockdriver:1.0-SNAPSHOT
    - TESTNAME="test_integration.HsqldbTest test_integration.PropertiesDriverArgsPassingTest" JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - TESTNAME=test_integration.SqliteXerialTest JDBC_DRIVER=org.xerial:sqlite-jdbc:3.7.2

matrix:
  include:
    - python: 2.7
      env: TESTNAME=test_integration.SqlitePyTest
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7.0 TESTNAME="test_integration.HsqldbTest  test_integration.PropertiesDriverArgsPassingTest" JDBC_DRIVER=org.hsqldb:hsqldb:1.8.0.10
    - python: 2.7
      env: JYTHON=org.python:jython-installer:2.7.0 TESTNAME=test_mock JDBC_DRIVER=org.jaydebeapi:mockdriver:1.0-SNAPSHOT

before_install:
  - ci/before_install.sh

install:
  - if [ "$JDBC_DRIVER" == "org.jaydebeapi:mockdriver:1.0-SNAPSHOT" ]; then (cd mockdriver && mvn install) ;fi
  - if [ -n "$JDBC_DRIVER" ]; then envsubst < ci/dot_jip > $VIRTUAL_ENV/.jip && pip install jip==0.9.3 && jip install $JDBC_DRIVER && export CLASSPATH=$VIRTUAL_ENV/javalib/* ;fi # TODO: Fix jip to search for local maven repo without twaking .jip
  - source $HOME/myvirtualenv/bin/activate
  - pip install -e .
  - pip install coveralls

script:
  - PY="coverage run --source jaydebeapi"
  - $PY test/testsuite.py $TESTNAME
  - if [ "$JDBC_DRIVER" == "org.hsqldb:hsqldb:1.8.0.10" ] ; then $PY test/doctests.py ;fi

after_success:
# TODO remove hack
  - if [ -z "$JYTHON" ]; then coveralls ; else deactivate && source ~/virtualenv/python/${TRAVIS_PYTHON_VERSION}/bin/activate && pip install coveralls && coveralls ; fi
